feat: 이력서 참고링크 api 구현
resumeme/Backend pull request #129
Opened 2023-11-06 17:04 UTC by beomukim

##  🖥️  이런 PR 입니다
이력서 참고링크 조회, 수정 api 구현입니다

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-06 17:35 UTC, ddongpuri approved these changes

2023-11-07 02:18 UTC, Juhongseok requested changes
수정 좀만 해주세요

2023-11-07 02:18 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/resume/domain/ReferenceLink.java
> +
`@Enumurated()` 빠졌어요

2023-11-07 02:18 UTC, Juhongseok commented on src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
> +                                )
`pathParameters()`에 대한 것도 넣어주세요

2023-11-07 05:31 UTC, Juhongseok approved these changes

2023-11-07 05:32 UTC, merged