feat: 메일 보내기 기능 구현
resumeme/Backend pull request #156
Opened 2023-11-10 16:03 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- 단순 메일 보내기 기능 구현입니다. (전송 실패시 재전송 기능 미구현)

## CC. 리뷰어
- 누추한 html 이해부탁드려요..
- 공통 속성을 뺀다면, 아마 html도 하나로 활용 가능할 듯 합니다

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-10 16:06 UTC, beomukim approved these changes
👍

2023-11-11 06:03 UTC, Juhongseok requested changes
html파일은 만들 이유가 없어보여요
메일로 알림이 다 갔는데 한번더 보여줘야 할까요?

2023-11-11 13:14 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/business/mail/service/EmailInfoGenerator.java
> +        String[] to = menteeList.toArray(new String[menteeList.size()]);
messageHelper.setTo()가 파라미터로 List를 못받는것 같아서 변환했어요

2023-11-11 13:16 UTC, ddongpuri commented
> html파일은 만들 이유가 없어보여요 메일로 알림이 다 갔는데 한번더 보여줘야 할까요?

메일 본문에 해당 알림에 대한 내용을 확인할 수 있는 링크를 제공하면 좋을 것 같다고 생각했어요!

2023-11-12 05:58 UTC, Juhongseok commented
> 메일 본문에 해당 알림에 대한 내용을 확인할 수 있는 링크를 제공하면 좋을 것 같다고 생각했어요!

그럼 그냥 메일 본문에 알림 내용을 적어주면 안되나요?

2023-11-13 04:18 UTC, Juhongseok approved these changes

2023-11-13 05:14 UTC, merged