feat: 기간별 합격률 계산 기능 구현
resumeme/Backend pull request #159
Opened 2023-11-11 07:32 UTC by beomukim

##  🖥️  이런 PR 입니다
기간별 합격률 계산 기능 구현입니다

## CC. 리뷰어
합격 관련 필드 embedded 클래스로 분리하였습니다. 관련 데이터를 어떻게 저장하고 활용할지는 미지수라 마음껏 의견 남겨주세요.

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-11 07:38 UTC, Juhongseok requested changes
PassInfo를 별도의 도메인으로 분리해주세요
이력서랑 통계수치는 따로 관리가 되어야 할 거 같아요

2023-11-13 03:43 UTC, Juhongseok requested changes

2023-11-13 03:43 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
양방향 매핑은 제거해주세요
이력서 쪽에서 통계수치를 몰라도 될거 같아요

2023-11-13 05:19 UTC, ddongpuri approved these changes

2023-11-13 06:34 UTC, Juhongseok approved these changes

2023-11-13 07:00 UTC, merged