feat: 로그아웃 기능 구현
resumeme/Backend pull request #161
Opened 2023-11-13 06:51 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- Refresh Token을 삭제하여 로그아웃 처리

## CC. 리뷰어

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-13 06:51 UTC, Juhongseok approved these changes

2023-11-13 06:52 UTC, Juhongseok approved these changes

2023-11-13 06:52 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/user/controller/UserController.java
> +    @PostMapping("/logout")
delete?
로그인 상태를 지우는 거니까요

2023-11-13 08:39 UTC, beomukim approved these changes

2023-11-13 08:47 UTC, Juhongseok requested changes
logoutfilter에 logouthandler로 써도 될거 같아요

2023-11-14 05:21 UTC, Juhongseok approved these changes

2023-11-14 05:29 UTC, merged