feat: 이력서 첨삭 완료 기능 구현
resumeme/Backend pull request #167
Opened 2023-11-14 08:11 UTC by beomukim

##  🖥️  이런 PR 입니다
이력서 첨삭 완료 기능 구현입니다

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-14 16:43 UTC, ddongpuri requested changes
총평 완료 상태인 건에 대해서 또 총평을 남기는 걸 막을 수 있는 로직이 필요할 것 같아요

2023-11-14 19:40 UTC, Juhongseok requested changes

2023-11-14 19:40 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java
> +    }
이전 상태가 종료를 시킬 수 있는지 확인을 해주면 좋겠네요

2023-11-14 19:40 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
> +                .orElseThrow(() -> new CustomException(RESUME_NOT_FOUND));
K3: 이런건 인라인 처리해줘도 괜찮을 거 같아요

2023-11-14 19:40 UTC, Juhongseok commented on src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
API Docs 반영 해주세요

2023-11-15 06:11 UTC, ddongpuri approved these changes

2023-11-15 06:11 UTC, Juhongseok approved these changes

2023-11-15 06:41 UTC, merged