fix: 멘토/멘티 조회 response role 값 수정 및 삭제
resumeme/Backend pull request #169
Opened 2023-11-14 16:45 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- 기존에 "ROLE_XXX" 형태로 넘어가던 역할 "mentor", "mentee", "pending" 으로 교체
- 멘토/멘티 일반 단건 조회의 경우 이미 역할을 알고 있어야 요청을 보낼 수 있기 때문에 response 에서 삭제

## CC. 리뷰어

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-14 19:37 UTC, Juhongseok requested changes

2023-11-14 19:37 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java
> +        this(mentor.getImageUrl(), mentor.getRequiredInfo().getRealName(), mentor.getRequiredInfo().getNickname(), mentor.getRequiredInfo().getPhoneNumber(), mentor.getRequiredInfo().getRole().equals
3항 연산자 제거하고 도메인 내부에서 반환하도록 변경해주세요

2023-11-15 04:23 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java
> +        this(mentor.getImageUrl(), mentor.getRequiredInfo().getRealName(), mentor.getRequiredInfo().getNickname(), mentor.getRequiredInfo().getPhoneNumber(), mentor.getRequiredInfo().getRole().equals
[fix: 불필요한 삼항연산자 제거](https://github.com/resumeme/Backend/pull/169/commits/87ea7e76d9e18e5832b56b537d9a8e8b8b85c5d3)

2023-11-15 05:16 UTC, beomukim approved these changes

2023-11-15 06:12 UTC, Juhongseok approved these changes

2023-11-15 06:51 UTC, merged