feat: 사용자는 카카오 로그인을 사용하여 가입을 할 수 있다
resumeme/Backend pull request #24
Opened 2023-10-22 11:04 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- 소셜 로그인을 통한 서비스 회원가입 기능입니다.
- 소셜 로그인 완료 (ROLE == GUEST) -> 필수 추가정보 기입 (멘티 선택 -> ROLE == MENTEE, 멘토 선택 -> ROLE == TEMP)
- jwt 토큰 발행 관련 코드는 완성되는대로 빠르게 추가 commit 하겠습니다. 죄송합니다ㅠㅠ

## CC. 리뷰어
Mentee, Mentor 에 들어가는 값들에 큰 차이가 없어서 클래스를 User로 통일하려고 합니다. 
멘토, 멘티 클래스는 추후 삭제하겠습니다.

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-10-22 13:41 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/controller/UserController.java
> +
개행 ❌

2023-10-22 13:42 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/controller/UserController.java
> +        return new ResponseEntity<>(savedUserId, HttpStatus.OK);
ResponseEntity 사용 안하기로 한거 아닌가요?

2023-10-22 13:43 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/domain/user/Role.java
> +    ROLE_PENDING, // 소셜로그인 후 추가 필수 정보 기입 (멘토) + 멘토 승인 요청 보내고 심사 대기중
두개가 분리되야하는 이유가 있을까요?

2023-10-22 13:43 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/domain/user/Role.java
> +    ROLE_PENDING, // 소셜로그인 후 추가 필수 정보 기입 (멘토) + 멘토 승인 요청 보내고 심사 대기중
어차피 할수 있는 작업은 같지않을까요?

2023-10-22 13:45 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/domain/user/User.java
> +    // 추가 필수 정보
주석들은 제거해주세요

2023-10-22 13:46 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/domain/user/User.java
> +    private String username; // google_{고유번호}
username은 아래 realname이랑 많이 헷갈리네요 차라리 oauth가 들어가서 소셜에서 제공되었다는 걸 나타내는 건 어떤가요?

2023-10-22 13:56 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
> +        }
나중에 분기문 refactoring이 필요하겠네요

2023-10-22 13:58 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
> +        String provider = userRequest.getClientRegistration().getRegistrationId(); // google
registrationId를 두번이나 받고있군요⁉️🤔

2023-10-22 13:59 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
> +        }
나중에 리팩토링도 하는걸로

2023-10-22 14:01 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/repository/UserRepository.java
> +    User findByUsername(String username);
이부분에서 Optional로 받는게 좋아보이네요 nullPointer 주의

2023-10-22 14:01 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java
> +
개행 ❌

2023-10-22 14:01 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java
> +            throw e;
의미없는 예외던지기?!

2023-10-22 14:02 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/PrincipalDetails.java
클래스명을 다른걸로 하는건 어떤가요?
OAuthUser나 다른걸로?

2023-10-22 14:03 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/PrincipalDetails.java
> +public class PrincipalDetails implements UserDetails, OAuth2User {
UserDetails는 왜 상속받으신거죠?
OAuth만 사용하는 것 아닌가요?

2023-10-22 14:04 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/PrincipalDetails.java
> +        return collect;
```suggestion
        return List.of(() -> String.valueOf(user.getRole));
```
람다써서 줄일 수 있어요

2023-10-22 14:06 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/userInfo/KakaoOAuth2UserInfo.java
> +        return profile.get("nickname").toString();
return 문 이전 개행

2023-10-22 14:08 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/service/UserService.java
> +                .orElseThrow(() -> new NoSuchElementException("해당 아이디의 회원이 없습니다."));
비지니스 로직에서 CustomException 사용하기로 한거 아닌가요?

2023-10-22 14:10 UTC, Juhongseok requested changes
고생하셨어요
기본 개발 코드도 많으니 테스트코드는 분리해서 pr을 다시 올리는게 좋을 거 같네요

2023-10-23 03:01 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/domain/user/Role.java
> +    ROLE_PENDING, // 소셜로그인 후 추가 필수 정보 기입 (멘토) + 멘토 승인 요청 보내고 심사 대기중
멘토 심사 요청을 이미 보냈으면, 다시 보낼 수 없다고 생각해서 상태를 하나 더 두었습니다
그 차이밖에 없어서 TEMP, PENDING 하나로 통일해도 될 것 같습니다

2023-10-23 03:11 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/global/auth/userInfo/KakaoOAuth2UserInfo.java
> +        return profile.get("nickname").toString();
[chore : 주석 삭제 및 개행 수정](https://github.com/resumeme/Backend/pull/24/commits/9a28c42ed1282194ad7c74a446e798f677286dd1)

2023-10-23 03:11 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java
> +
[chore : 주석 삭제 및 개행 수정](https://github.com/resumeme/Backend/pull/24/commits/9a28c42ed1282194ad7c74a446e798f677286dd1)

2023-10-23 03:11 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/domain/user/User.java
> +    // 추가 필수 정보
[chore : 주석 삭제 및 개행 수정](https://github.com/resumeme/Backend/pull/24/commits/9a28c42ed1282194ad7c74a446e798f677286dd1)

2023-10-23 03:11 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/controller/UserController.java
> +
[chore : 주석 삭제 및 개행 수정](https://github.com/resumeme/Backend/pull/24/commits/9a28c42ed1282194ad7c74a446e798f677286dd1)

2023-10-23 03:19 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/domain/user/User.java
> +    private String username; // google_{고유번호}
[fix : username -> oAuthUsername 변경](https://github.com/resumeme/Backend/pull/24/commits/52ce71b2f328bc7f660358e0139258b9012a8861)

2023-10-23 04:06 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java
> +        String provider = userRequest.getClientRegistration().getRegistrationId(); // google
[fix : findByOauthUsername 관련 변경 및 리팩토링](https://github.com/resumeme/Backend/pull/24/commits/92a19530f80177179c91308f85bc0761ce8ba6fb)

2023-10-23 04:10 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/repository/UserRepository.java
> +    User findByUsername(String username);
Optional 처리 했습니다!

2023-10-23 04:15 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/global/auth/PrincipalDetails.java
> +public class PrincipalDetails implements UserDetails, OAuth2User {
일반 로그인 기능 필요할까봐 상속받았는데 일단 지우겠습니다!

2023-10-23 05:13 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java
> +            throw e;
[fix : CustomException 사용](https://github.com/resumeme/Backend/pull/24/commits/bef9cd920cb3882b29977700bdbaf6a9da499f79)

2023-10-23 05:19 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/service/UserService.java
> +                .orElseThrow(() -> new NoSuchElementException("해당 아이디의 회원이 없습니다."));
[fix : CustomException 사용](https://github.com/resumeme/Backend/pull/24/commits/bef9cd920cb3882b29977700bdbaf6a9da499f79)

2023-10-23 06:47 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/controller/UserController.java
> +        return new ResponseEntity<>(savedUserId, HttpStatus.OK);
이부분 아직 변경이 안됐네요
단순 200반환이면 body data만 넘겨줘도 됩니다
전에 구두로만 이야기가 나눴는지 컨벤션에는 없었네요

2023-10-23 06:49 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/domain/user/Role.java
> +    ROLE_PENDING, // 소셜로그인 후 추가 필수 정보 기입 (멘토) + 멘토 승인 요청 보내고 심사 대기중
통일하는 걸로 결정이 된거죠?

2023-10-23 06:49 UTC, Juhongseok reviewed
코멘트 남겼어요 확인부탁드려요

2023-10-23 06:56 UTC, beomukim approved these changes
수고하셨어요~ 멘티 멘토 클래스는 제 pr에서 삭제했습니다

2023-10-23 07:06 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/controller/UserController.java
> +        return new ResponseEntity<>(savedUserId, HttpStatus.OK);
[fix : ResponseEntity 사용 제거](https://github.com/resumeme/Backend/pull/24/commits/c645dee831c7bff76f2ec4bec07b08c1d0440c71)

2023-10-23 07:06 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/repository/UserRepository.java
> +    Optional<User> findByOauthUsername(String oauthUsername);
[chore : 개행 추가](https://github.com/resumeme/Backend/pull/24/commits/74a745abfb7edff1e37fae872f991409257f6725)

2023-10-23 07:07 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/domain/user/Role.java
> +    ROLE_PENDING, // 소셜로그인 후 추가 필수 정보 기입 (멘토) + 멘토 승인 요청 보내고 심사 대기중
[fix : 불필요한 역할 제거 및 CustomException 추가] ROLE_TEMP 제거했습니다 (https://github.com/resumeme/Backend/pull/24/commits/fcf0c32f92c017716edd007ee1b66102b3c03d36)

2023-10-23 09:45 UTC, Juhongseok approved these changes
👍

2023-10-23 10:05 UTC, merged