feat: 인증, 인가 관련 에러 분리
resumeme/Backend pull request #257
Opened 2023-11-21 15:53 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- 로그인이 필요한 경우 401, 권한이 올바르지 않은 경우 400 을 던지도록 로직 수정

## CC. 리뷰어

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-21 16:06 UTC, Juhongseok approved these changes

2023-11-21 16:07 UTC, beomukim approved these changes

2023-11-21 16:14 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
>                      throw new TokenException(INVALID_ACCESS_TOKEN);
이 경우도 없어도 될거 같아요
로그인 안한 사용자가 토큰이 둘다 없이 접근할 수 있는 엔드포인트가 있는데 이러면 접근을 못하지않을까요?

2023-11-21 16:14 UTC, Juhongseok requested changes
하나만 다시 봐주세요

2023-11-21 16:45 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
>                      throw new TokenException(INVALID_ACCESS_TOKEN);
액세스 토큰이 존재하지 않을 경우, 바로 doFilter로 가게끔 하는 코드가 있어
현재 로그인하지 않은 사용자도 허용된 엔드포인드에 한해서는 접근이 가능합니다!

2023-11-22 01:13 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
>                      throw new TokenException(INVALID_ACCESS_TOKEN);
그러면 checkRefreshToken에서 accesstoken존재여부 검증 로직을제거하고 ifPreseOrelse구문에서 else 문을 없애면요??
그렇게 되면 메소드가 하나의 기능을 하게끔 바뀔 수 도 있을 거 같아요

2023-11-22 04:43 UTC, Juhongseok approved these changes

2023-11-23 03:54 UTC, merged