feat: 관심멘토 설정 기능
resumeme/Backend pull request #272
Opened 2023-11-23 12:44 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- 팔로우와 멘토, 멘티 사이 연관관계 삭제 -> id 값으로 대체
- 팔로우 가능한 최대 멘토 수는 3명으로 제한

## CC. 리뷰어
- 이전 PR과 내용은 거의 비슷하고, 연관관계는 끊었습니다.

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-23 13:02 UTC, beomukim approved these changes

2023-11-23 13:06 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java
> +
아이디만 주면 어떻게 사용해요?

2023-11-23 13:29 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java
> +
생각해보니 쓸일이 없는 api네요 지울게요~

2023-11-24 04:02 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java
> +
@ddongpuri
[feat: 팔로우하는 멘토 전체 조회시 리턴값 변경](https://github.com/resumeme/Backend/pull/272/commits/b60089d2317ae7445c794d9f9165ab31e05350f0)

2023-11-24 04:27 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java
> +                .map(follow -> new FollowResponse(follow, mentorService.getOne(follow.getMentorId())))
이렇게 하면 팔로우한 멘토 수만큼 계속 조회 쿼리가 나갈텐데 차라리 mentor 아이디리스트로 `where mentorId in (ids)` 해당 조건을 걸어서 한번에 미리 가지고 오는건 어떤가요

2023-11-24 15:20 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java
> +                .map(follow -> new FollowResponse(follow, mentorService.getOne(follow.getMentorId())))
[fix: 팔로우 중인 멘토 조회쿼리 개선](https://github.com/resumeme/Backend/pull/272/commits/5ad2681e30fbccaa347917fe9c0d1e34559705ca)

2023-11-25 01:54 UTC, Juhongseok requested changes

2023-11-25 01:54 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/user/service/mentee/FollowService.java
> +        if (followList.size() > MAX_FOLLOW_SIZE - 1) {
1명만 팔로우 할 수 있는거 아닌가요?

2023-11-25 01:54 UTC, Juhongseok commented on src/main/resources/application-endpoint.yml
get, post도 추가해야겠네요

2023-11-25 04:55 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/business/user/service/mentee/FollowService.java
> +        if (followList.size() > MAX_FOLLOW_SIZE - 1) {
3명까지 팔로우 가능입니당

2023-11-25 05:15 UTC, ddongpuri commented on src/main/resources/application-endpoint.yml
[chore: 누락된 엔드포인트 추가](https://github.com/resumeme/Backend/pull/272/commits/1df0448e3867ed2426aacea1aa7ba3c374725247)

2023-11-25 09:38 UTC, Juhongseok approved these changes

2023-11-25 11:16 UTC, merged