feat: 특정 멘토 팔로우 여부 단건 조회 기능 구현
resumeme/Backend pull request #298
Opened 2023-11-27 19:05 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- 이벤트 상세조회 페이지에서 해당 멘토에 대한 팔로우 여부를 나타낼때 필요한 api

## CC. 리뷰어

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-11-27 21:34 UTC, Juhongseok requested changes

2023-11-27 21:34 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java
> +        return optionalFollow.map(follow -> new IdResponse(follow.getId())).orElseGet(() -> new IdResponse(null));
orElse 구문도 서비스로 넣어주세요

2023-11-28 04:34 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java
> +        return optionalFollow.map(follow -> new IdResponse(follow.getId())).orElseGet(() -> new IdResponse(null));
[refactor: 로직 내부화](https://github.com/resumeme/Backend/pull/298/commits/45b8afff6f0b6d5403d46f618d8255f51ff0a4d3)

2023-11-28 04:52 UTC, Juhongseok approved these changes

2023-11-28 05:01 UTC, beomukim approved these changes

2023-11-28 05:08 UTC, merged