feat: jwt 토큰 검증
resumeme/Backend pull request #52
Opened 2023-10-27 07:48 UTC by ddongpuri

##  🖥️  이런 PR 입니다
- 회원가입 후 로그인 시 access, refresh 토큰 발급 및 반환
- 회원가입 시 request는 추후 프론트 로그인 담당자과 이야기 나눠서 변경될 수 있습니다

## CC. 리뷰어

## 테스트 설명

## 기타
**Prefix**

PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.

- K1: 꼭 반영해주세요 (Request changes)
- K2: 웬만하면 반영해 주세요 (Comment)
- K3: 그냥 사소한 의견입니다 (Approve)

2023-10-27 08:16 UTC, beomukim approved these changes

2023-10-27 11:56 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/controller/MenteeController.java
> +
공백 ?

2023-10-27 11:58 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/controller/dto/RegisterInfo.java
> +public record RegisterInfo(String cacheKey, RequiredInfo requiredInfo) {
RequiredInfo도 DTO로 분리해주세요

2023-10-27 11:58 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
> +                log.info("if present222 ==========");
log 제거

2023-10-27 11:59 UTC, Juhongseok commented on src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java
> +        return Map.of("access", accessToken, "refresh", refreshToken);
한줄 개행

2023-10-27 11:59 UTC, Juhongseok requested changes
DTO 분리작업만 추가해주세요
리팩토링은 다음에 진행하죠

2023-10-27 16:38 UTC, ddongpuri commented on src/main/java/org/devcourse/resumeme/controller/dto/RegisterInfo.java
> +public record RegisterInfo(String cacheKey, RequiredInfo requiredInfo) {
[fix: 사용자 필수정보 dto 생성](https://github.com/resumeme/Backend/pull/52/commits/10e825df30bcaba99e791e71c254388b16805811)

2023-10-28 00:25 UTC, Juhongseok approved these changes
👍

2023-10-28 00:30 UTC, merged